
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:9 (project)"
    message: |
      The target system is: Generic -  - ARM
      The host system is: Darwin - 22.6.0 - arm64
  -
    kind: "message-v1"
    backtrace:
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:9 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /Users/joshua_beard/Desktop/titan/dev/arm_gcc_toolchain/13.3 rel1/bin/arm-none-eabi-gcc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      permission denied
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:9 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /Users/joshua_beard/Desktop/titan/dev/arm_gcc_toolchain/13.3 rel1/bin/arm-none-eabi-gcc.exe 
      Build flags: 
      Id flags: -c 
      
      The output was:
      permission denied
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:9 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /Users/joshua_beard/Desktop/titan/dev/arm_gcc_toolchain/13.3 rel1/bin/arm-none-eabi-gcc.exe 
      Build flags: 
      Id flags: -Aa 
      
      The output was:
      permission denied
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:9 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /Users/joshua_beard/Desktop/titan/dev/arm_gcc_toolchain/13.3 rel1/bin/arm-none-eabi-gcc.exe 
      Build flags: 
      Id flags: -D__CLASSIC_C__ 
      
      The output was:
      permission denied
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:9 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /Users/joshua_beard/Desktop/titan/dev/arm_gcc_toolchain/13.3 rel1/bin/arm-none-eabi-gcc.exe 
      Build flags: 
      Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3 
      
      The output was:
      permission denied
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:9 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /Users/joshua_beard/Desktop/titan/dev/arm_gcc_toolchain/13.3 rel1/bin/arm-none-eabi-gcc.exe 
      Build flags: 
      Id flags: -c;-I__does_not_exist__ 
      
      The output was:
      permission denied
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:9 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /Users/joshua_beard/Desktop/titan/dev/arm_gcc_toolchain/13.3 rel1/bin/arm-none-eabi-gcc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      permission denied
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:9 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /Users/joshua_beard/Desktop/titan/dev/arm_gcc_toolchain/13.3 rel1/bin/arm-none-eabi-gcc.exe 
      Build flags: 
      Id flags: -c 
      
      The output was:
      permission denied
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:9 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /Users/joshua_beard/Desktop/titan/dev/arm_gcc_toolchain/13.3 rel1/bin/arm-none-eabi-gcc.exe 
      Build flags: 
      Id flags: -Aa 
      
      The output was:
      permission denied
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:9 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /Users/joshua_beard/Desktop/titan/dev/arm_gcc_toolchain/13.3 rel1/bin/arm-none-eabi-gcc.exe 
      Build flags: 
      Id flags: -D__CLASSIC_C__ 
      
      The output was:
      permission denied
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:9 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /Users/joshua_beard/Desktop/titan/dev/arm_gcc_toolchain/13.3 rel1/bin/arm-none-eabi-gcc.exe 
      Build flags: 
      Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3 
      
      The output was:
      permission denied
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:9 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /Users/joshua_beard/Desktop/titan/dev/arm_gcc_toolchain/13.3 rel1/bin/arm-none-eabi-gcc.exe 
      Build flags: 
      Id flags: -c;-I__does_not_exist__ 
      
      The output was:
      permission denied
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:1205 (message)"
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:86 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:9 (project)"
    message: |
      Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
  -
    kind: "message-v1"
    backtrace:
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:1205 (message)"
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:86 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:9 (project)"
    message: |
      Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
  -
    kind: "message-v1"
    backtrace:
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:9 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: /Library/Developer/CommandLineTools/usr/bin/CC 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      ld: library 'System' not found
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:9 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /Library/Developer/CommandLineTools/usr/bin/CC 
      Build flags: 
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.o"
      
      The CXX compiler identification is AppleClang, found in:
        /Users/joshua_beard/Desktop/titan/cmake-build-debug/CMakeFiles/3.30.3/CompilerIdCXX/CMakeCXXCompilerId.o
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeDetermineCompilerABI.cmake:74 (try_compile)"
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:9 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/Users/joshua_beard/Desktop/titan/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-Qketvc"
      binary: "/Users/joshua_beard/Desktop/titan/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-Qketvc"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: ""
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/Users/joshua_beard/Desktop/titan/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-Qketvc'
        
        Run Build Command(s): /Users/joshua_beard/Applications/CLion.app/Contents/bin/ninja/mac/aarch64/ninja -v cmTC_585d6
        [1/2] "/Users/joshua_beard/Desktop/titan/dev/arm_gcc_toolchain/13.3 rel1/bin/arm-none-eabi-gcc.exe"    -o CMakeFiles/cmTC_585d6.dir/CMakeCCompilerABI.c.obj -c /Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeCCompilerABI.c
        FAILED: CMakeFiles/cmTC_585d6.dir/CMakeCCompilerABI.c.obj 
        "/Users/joshua_beard/Desktop/titan/dev/arm_gcc_toolchain/13.3 rel1/bin/arm-none-eabi-gcc.exe"    -o CMakeFiles/cmTC_585d6.dir/CMakeCCompilerABI.c.obj -c /Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeCCompilerABI.c
        /bin/sh: /Users/joshua_beard/Desktop/titan/dev/arm_gcc_toolchain/13.3 rel1/bin/arm-none-eabi-gcc.exe: Permission denied
        ninja: build stopped: subcommand failed.
        
      exitCode: 1
  -
    kind: "try_compile-v1"
    backtrace:
      - "/Users/joshua_beard/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.30/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:9 (project)"
    checks:
      - "Check for working C compiler: /Users/joshua_beard/Desktop/titan/dev/arm_gcc_toolchain/13.3 rel1/bin/arm-none-eabi-gcc.exe"
    directories:
      source: "/Users/joshua_beard/Desktop/titan/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-AJNvSp"
      binary: "/Users/joshua_beard/Desktop/titan/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-AJNvSp"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: ""
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: '/Users/joshua_beard/Desktop/titan/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-AJNvSp'
        
        Run Build Command(s): /Users/joshua_beard/Applications/CLion.app/Contents/bin/ninja/mac/aarch64/ninja -v cmTC_a2a88
        [1/2] "/Users/joshua_beard/Desktop/titan/dev/arm_gcc_toolchain/13.3 rel1/bin/arm-none-eabi-gcc.exe"    -o CMakeFiles/cmTC_a2a88.dir/testCCompiler.c.obj -c /Users/joshua_beard/Desktop/titan/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-AJNvSp/testCCompiler.c
        FAILED: CMakeFiles/cmTC_a2a88.dir/testCCompiler.c.obj 
        "/Users/joshua_beard/Desktop/titan/dev/arm_gcc_toolchain/13.3 rel1/bin/arm-none-eabi-gcc.exe"    -o CMakeFiles/cmTC_a2a88.dir/testCCompiler.c.obj -c /Users/joshua_beard/Desktop/titan/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-AJNvSp/testCCompiler.c
        /bin/sh: /Users/joshua_beard/Desktop/titan/dev/arm_gcc_toolchain/13.3 rel1/bin/arm-none-eabi-gcc.exe: Permission denied
        ninja: build stopped: subcommand failed.
        
      exitCode: 1
...
